apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: webtree
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
        server_name example.com;
        return 301 $scheme://www.example.com$request_uri;
      }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webtree-redirect
  namespace: webtree
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: log
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: webtree-redirect
  namespace: webtree
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webtree-redirect
  namespace: webtree
spec:
  rules:
    - host: webtree.org
      http:
        paths:
          - backend:
              serviceName: webtree-redirect
              servicePort: http
